* README

My personal dotfiles.

I aim to be as lean and straightforward as possible.

I currently use zsh with [[https://github.com/sindresorhus/pure][pure prompt]] and [[https://github.com/base16-project/base16-shell][base16 shell themes]].

I used to use [[https://ohmyz.sh/][oh-my-zsh]] but stopped because I was only using it for prompts and themes. Making my own prompt and theme is a lot of work, so I like to pull in code for that.

~setup.org~ tries it's best to pull in everything needed for this setup. Not everything is there yet, but I hope to update it overtime.

My approach to ~setup.org~ is also similar to my dotfiles. There are many different tools I could use for this, but I prefer to be simple. It's just for installing and updating, nothing more complicated than that!

* Setup

I use zsh and daily drive MacOS. I hope to add specific Linux support since I used to use Linux as a daily driver and will be using it on my other machines.

If you'd like to use this yourself, run these commands:
#+BEGIN_SRC sh
git clone https://github.com/cyrialize/dotfiles.git "$HOME/Code/dotfiles"
source $HOME/Code/dotfiles/setup.sh
#+END_SRC