* README
My personal dotfiles.

I aim to be as lean and straightforward as possible.

I currently use zsh with [[https://github.com/sindresorhus/pure][pure prompt]] and [[https://github.com/base16-project/base16-shell][base16 shell themes]].

I used to use [[https://ohmyz.sh/][oh-my-zsh]] but stopped because I was only using it for prompts and themes. Making my own prompt and theme is a lot of work, so I like to pull in code for that.

~setup.sh~ tries it's best to pull in everything needed for this setup. Not everything is there yet, but I hope to update it overtime.

My approach to ~setup.sh~ is also similar to my dotfiles. There are many different tools I could use for this, but I prefer to be simple. It's just for installing and updating, nothing more complicated than that!

* Setup
I use zsh and daily drive MacOS. I hope to add specific Linux support since I used to use Linux as a daily driver and will be using it on my other machines.

If you'd like to use this yourself, run these commands:
#+BEGIN_SRC sh
git clone https://github.com/cyrialize/dotfiles.git "$HOME/Code/dotfiles"
chmod +x $HOME/Code/dotfiles/setup.sh
$HOME/Code/dotfiles/setup.sh
#+END_SRC

* Usage
#+BEGIN_SRC
❯ ./setup.sh -h
Setup script for setting up my dotfiles. Intended for MacOS. Linux
support planned in the future.

Checks for OS support prior to running anything.

Usage:
--a Run all flags.
--i Run install.sh to install/update libs, pure, and base16-shell.
--l Connect symlinks.
--h See this message.
#+END_SRC

** Example Output
#+BEGIN_SRC
❯ ./setup.sh -a
On MacOS!
Symlink /Users/jonny/Code/dotfiles/.zshrc to /Users/jonny/.zshrc exists
Symlink /Users/jonny/Code/dotfiles/.global_gitconfig to /Users/jonny/.gitconfig exists
Pure prompt is already installed!
Updating...
Already up to date.
base16 shell themes are already installed!
Updating...
Already up to date.
Installing/Updating 4 applications
----------
Already installed: fortune
Version: fortune 9708
----------
Already installed: cowsay
Version: cowsay 3.04_1
----------
Already installed: ripgrep
Version: ripgrep 13.0.0
----------
Already installed: font-hack
----------
#+END_SRC